// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxmrur0y4BKTQwk1CoRgVNJQlM7rre04M',
    appId: '1:324145816070:web:fdd1879b19aacc20165987',
    messagingSenderId: '324145816070',
    projectId: 'mini-whatsapp-76d1a',
    authDomain: 'mini-whatsapp-76d1a.firebaseapp.com',
    storageBucket: 'mini-whatsapp-76d1a.appspot.com',
    measurementId: 'G-8R8PM8REVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxijyczArlqxHYMQxPkObnV2dwwJSqE3E',
    appId: '1:324145816070:android:ab3cabfe646d14e1165987',
    messagingSenderId: '324145816070',
    projectId: 'mini-whatsapp-76d1a',
    storageBucket: 'mini-whatsapp-76d1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJoMDrQwlzFWhxhLPR0Mk4Zi8VJ-ulME8',
    appId: '1:324145816070:ios:755cbcddf0d7ceac165987',
    messagingSenderId: '324145816070',
    projectId: 'mini-whatsapp-76d1a',
    storageBucket: 'mini-whatsapp-76d1a.appspot.com',
    iosBundleId: 'com.example.miniWhatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJoMDrQwlzFWhxhLPR0Mk4Zi8VJ-ulME8',
    appId: '1:324145816070:ios:755cbcddf0d7ceac165987',
    messagingSenderId: '324145816070',
    projectId: 'mini-whatsapp-76d1a',
    storageBucket: 'mini-whatsapp-76d1a.appspot.com',
    iosBundleId: 'com.example.miniWhatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxmrur0y4BKTQwk1CoRgVNJQlM7rre04M',
    appId: '1:324145816070:web:6a302dee606ede5a165987',
    messagingSenderId: '324145816070',
    projectId: 'mini-whatsapp-76d1a',
    authDomain: 'mini-whatsapp-76d1a.firebaseapp.com',
    storageBucket: 'mini-whatsapp-76d1a.appspot.com',
    measurementId: 'G-9ZJTFMJH7B',
  );

}